@startuml

class field{
    -isNull bool
	-data   []byte
    +{static} NewFieldFromBytes(bytes []byte) (*field, error)
    +{static} NewNullField() *field
    +FieldLen() int
    +FieldToBytes() ([]byte, error)
    +FieldIsNull() bool
    +SetFieldNull()
}



@enduml