@startuml

class Field{
    -isNull bool
	-data   []byte
    
    +{static} NewFieldFromBytes(bytes []byte) (*Field, error)
    +{static} NewNullField() *Field
    +FieldLen() int
    +FieldToBytes() ([]byte, error)
    +FieldIsNull() bool
    +SetFieldNull()
}

class Domain{
    -domainName string
	-domainType DomainType
	-n int32
	-d int32

    +{static} NewDomain(name string, t DomainType, inN int32, inD int32) (*Domain, error)
    +GetDomainName() string
    +GetDomainType() DomainType
    +GetDomainN() (int32, error)
    +GetDomainD() (int32, error)
    +DomainSizeUnfixed() bool
    +DomainSizeInBytes() (int, error)
}

class Schema{
    -tableName string
	-domains []*Domain
	-constraints []*Constraint

    +{static} NewSchema(name string, domainList []*Domain, constraintList []*Constraint) (*Schema, error)
    +UnfixedDomainNum() int
    +GetSchemaTableName() string
    +GetSchemaDomains() []*Domain
    +GetSchemaDomain(index int) (*Domain, error)
    +GetSchemaConstraints() []*Constraint
    +GetSchemaDomainNum() int
    +GetSchemaConstraintNum() int
}

class Tuple{
    -tableId uint32
	-pageId uint32
	-tupleId uint32
	-schema *Schema
	-fields []*Field

    +TupleSizeInBytes() int
    +TupleSizeFixed() bool
    +TupleToBytes() []byte
    +BytesToTuple(bytes []byte, s *Schema) *Tuple
    +GetTupleId() uint32
    +SetPageId(id uint32)

}

Schema o-- Domain
Tuple o-- Field
Tuple *-- Schema

@enduml