#line 1 "parser/calc.lexer.c"

#line 3 "parser/calc.lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 150
#define YY_END_OF_BUFFER 151
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[601] =
    {   0,
        0,    0,  151,  150,  149,  148,  150,  150,  142,  143,
       43,   50,  144,   51,   83,   52,  137,  137,  141,   77,
       75,   78,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  150,  148,  139,    0,    0,  137,
        0,    0,  137,  137,   79,   76,   80,  147,  147,  147,
      147,  147,    8,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,   90,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,   87,   70,
       73,  147,  147,  147,  147,  147,  147,  147,  147,  147,

       15,  147,   10,   82,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,   53,  137,  137,  138,  138,    5,
      147,   71,  147,   81,   72,  120,  147,   45,  147,  147,
       56,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,   28,  147,  147,  147,   23,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,   59,  147,  147,
      147,  147,   47,   46,  147,   22,  145,  147,  147,   20,
        0,  147,   93,  147,  147,  147,  147,  147,  147,  147,

      147,   21,  147,   92,  147,  147,   44,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,  147,  147,  147,  147,  147,  147,   85,   54,  147,
      147,  147,  147,  147,  147,  147,  147,   67,  147,  147,
      147,  147,  147,  121,  147,  147,  147,    3,   24,   88,
      147,  147,  147,  147,   99,  125,  147,  147,  119,  147,
      147,  147,  147,  147,  147,  147,  123,  127,   69,  147,
      147,    0,  146,  147,    0,    0,  147,  147,  147,  147,
      147,   63,  147,  147,  147,  147,  147,  147,  107,  147,
      147,  147,   86,   68,  147,  147,  140,  147,  147,  147,

      115,  147,  147,    7,   26,  147,   16,    4,  147,  147,
       27,  147,  147,   31,  147,  147,  147,   48,  147,  122,
      147,  147,  147,  147,  147,  147,  147,  147,  147,  147,
      147,   62,  147,  147,  147,  147,    9,  147,   94,  147,
      147,  147,  147,  133,  147,    0,  147,    0,    0,  147,
      126,  147,  147,  147,  147,  147,  128,  147,  147,  147,
      103,  147,    2,  147,  147,  134,  147,  147,  147,  147,
      110,  100,  147,   13,  147,  147,  105,  147,  147,    1,
       89,  147,  147,  147,  147,   19,  147,  147,  147,   84,
       74,  147,  147,    0,  131,  111,  147,   18,  147,  147,

      147,  147,    0,  147,    0,    0,    0,  147,  147,  147,
      147,   91,  147,  129,  147,  147,  108,  147,  147,   29,
       14,  102,  147,  147,  147,   58,  117,  147,   65,   95,
       42,  147,  147,  147,    0,  147,  147,    0,  147,    0,
       17,   60,  147,  124,    0,   66,    0,    0,    0,  147,
      147,  147,  147,   98,  147,  147,  147,  147,   11,   55,
      147,  147,  147,  147,  147,   49,    0,    0,   97,  130,
      147,    0,  147,    0,    0,    0,  132,  116,    0,  147,
      147,  106,   61,  147,  147,  112,    6,  147,  147,  147,
      147,    0,    0,  113,  147,    0,  147,    0,    0,    0,

        0,   96,  147,  147,   25,  147,  109,   57,   41,  147,
      135,    0,    0,  118,    0,  147,    0,    0,    0,    0,
      114,   33,  147,  147,    0,    0,   32,  101,  147,    0,
        0,    0,   30,   12,  104,    0,    0,  136,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   34,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   64,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       39,    0,   37,    0,    0,    0,    0,    0,    0,    0,
       40,   38,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   35,    0,   36,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    1,    1,    1,    1,    6,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   16,
       16,   16,   16,   16,   16,   16,   16,    1,   17,   18,
       19,   20,    1,    1,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
        1,    1,    1,    1,   47,    1,   21,   22,   23,   24,

       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   46,    1,   48,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[49] =
    {   0,
        1,    1,    1,    2,    3,    4,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,    1,    1,    1,    1,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    1
    } ;

static const flex_int16_t yy_base[605] =
    {   0,
        0,    0, 1073, 1074, 1074,    0, 1067, 1065, 1074, 1074,
     1074, 1074, 1074, 1054, 1074, 1074, 1056,   36, 1074,   34,
     1074, 1049,   46,   52,   54,   65,   70,   75,   55,   62,
       72,   64, 1063,   80,   97,  104,  108,  115,  119,  127,
      137,  123,  143,   69, 1018,    0, 1074, 1060, 1058,   45,
       47,   49,  117,  122, 1074, 1074, 1074, 1059,  139,  111,
      146,  152,  156,  157,  165,  166,  167,  169,  173,  170,
      183,  176,  177,  184,  186,  178,  185,  192,  189,  181,
      195,  205,  196,  209,  217,  222,  218,  223, 1058,  234,
     1057,  228,  225,  229,  226,  230,  231,  232,  236,  235,

     1056,  237,  117,  242,  238,  240,  255,  268,  273,  277,
      278,  245,  281,  279,  282,  288,  283,  293,  292,  287,
      294,  291,  299,  301, 1074,  291,  312,  315,  317, 1055,
      311, 1054,  313, 1053, 1052, 1051,  321, 1050,  331,  333,
      246,  335,  336,  337,  338,  339,  340,  343,  344,  341,
      345,  346,  349,  348,  351,  347,  356,  350,  379,  352,
      359,  360, 1049,  353,  354,  382,  385,  387,  390,  391,
      355,  393,  394,  396,  395,  398,  400,  401,  402,  403,
      404,  405, 1048, 1047,  407, 1046,  409,  412,  413, 1045,
      391,  420,  424,  414,  423,  427,  415,  426,  433,  437,

      438, 1044,  442, 1043,  448,  450, 1042,  451,  453,  454,
      455,  457,  456,  458,  459,  460,  462,  469,  464,  467,
      468,  471,  472,  473,  465,  481,  490, 1041, 1040,  492,
      493,  496,  474,  478,  500,  504,  509, 1039,  508,  512,
      513,  515,  516, 1038,  520,  521,  523, 1037, 1036,  522,
      524,  527,  525,  528, 1035, 1034,  526,  531, 1033,  534,
      530,  532,  533,  538,  535,  542, 1032, 1031, 1030,  543,
      544, 1009, 1028,  554, 1006,  994,  555,  558,  545,  566,
      559, 1025,  567,  568,  571,  573,  574,  575, 1024,  577,
      582,  585, 1023, 1022,  581,  586, 1021,  587,  590,  594,

     1020,  597,  595,  596, 1019,  599, 1018, 1017,  598,  600,
     1016,  604,  605, 1015,  608,  610,  612, 1014,  614, 1013,
      615,  623,  624,  625,  626,  633,  628,  636,  642,  637,
      632, 1012,  641,  643,  648,  650,  639,  652, 1011,  645,
      655,  656,  651, 1010,  661,  988,  657,  980,  987,  671,
     1006,  665,  675,  679,  676,  680, 1005,  683,  684,  687,
     1004,  685,  688,  689,  690, 1003,  692,  694,  691,  701,
     1002, 1001,  702, 1000,  693,  695,  999,  703,  704,  998,
      997,  705,  698,  707,  724,  996,  708,  716,  731,  995,
      994,  717,  722,  975,  992,  991,  728,  737,  732,  738,

      740,  742,  968,  744,  968,  971,  969,  745,  746,  748,
      750,  749,  754,  986,  751,  755,  985,  758,  757,  984,
      983,  982,  759,  764,  765,  981,  980,  767,  979,  978,
      977,  760,  766,  762,  944,  769,  771,  934,  774,  949,
      973,  972,  775,  971,  949,  969,  932,  931,  925,  782,
      789,  783,  786,  965,  797,  800,  803,  804,  806,  964,
      807,  808,  809,  814,  810,  963,  928,  934,  811, 1074,
      812,  930,  813,  925,  937,  936, 1074,  956,  928,  822,
      823,  954,  953,  815,  820,  952,  818,  827,  816,  826,
      834,  930,  929,  949,  835,  912,  832,  913,  947,  946,

      923,  825,  828,  831,  943,  858,  942,  941,  940,  865,
      939,  919,  896,  936,  904,  859,  917,  898,  897,  890,
      930,  929,  862,  866,  903,  902, 1074, 1074,  867,  908,
      904,  903, 1074,  923,  922,  891,  885,  919,  890,  881,
      880,  890,  889,  892,  913,  912,  873,  877, 1074,   94,
      800,  878,  870,  882,  858,  877,  856,  875, 1074,  856,
      860,  852,  858,  856,  864,  854,  862,  852,  851,  861,
     1074,  860, 1074,  835,  855,  854,  874,  851,  850,  219,
     1074, 1074,  849,  840,  846,  792,  276,  274,  255,  221,
      145,   95,   97,   50,   43,   17, 1074,   30, 1074, 1074,

      900,  903,  905,  909
    } ;

static const flex_int16_t yy_def[605] =
    {   0,
      600,    1,  600,  600,  600,  601,  602,  603,  600,  600,
      600,  600,  600,  600,  600,  600,  601,  601,  600,  600,
      600,  600,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  600,  601,  600,  602,  603,  600,
      600,  600,  601,  601,  600,  600,  600,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,

      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  600,  600,  600,  600,  600,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      600,  604,  604,  604,  604,  604,  604,  604,  604,  604,

      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  600,  604,  604,  600,  600,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,

      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  600,  604,  600,  600,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  600,  604,  604,  604,  604,  604,  604,

      604,  604,  600,  604,  600,  600,  600,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  600,  604,  604,  600,  604,  600,
      604,  604,  604,  604,  600,  604,  600,  600,  600,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  604,  604,  600,  600,  604,  600,
      604,  600,  604,  600,  600,  600,  600,  604,  600,  604,
      604,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  600,  600,  604,  604,  600,  604,  600,  600,  600,

      600,  604,  604,  604,  604,  604,  604,  604,  604,  604,
      604,  600,  600,  604,  600,  604,  600,  600,  600,  600,
      604,  604,  604,  604,  600,  600,  600,  600,  604,  600,
      600,  600,  600,  604,  604,  600,  600,  604,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,    0,

      600,  600,  600,  600
    } ;

static const flex_int16_t yy_nxt[1123] =
    {   0,
        4,    5,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   33,   39,   40,   41,
       42,   43,   44,   33,   33,   33,   33,   45,   52,   46,
       53,   54,   55,   56,  599,   46,  598,   46,   46,  126,
      127,  128,  128,  129,  129,   46,  597,   46,   46,   59,
      596,   60,   46,   46,   68,   46,   65,   61,   46,   62,
       66,   69,   88,   46,   63,   73,   67,   64,   70,   74,
       78,   71,   87,   75,   72,   82,  124,   89,   92,   76,

       46,   79,   77,   80,   93,   90,   83,   46,   94,   84,
       91,   46,   85,   81,   46,   86,  554,   95,   46,  191,
       46,  595,   46,  594,   97,   96,   46,  555,   98,   52,
       46,   53,   53,  101,   52,  106,   53,   54,   99,  102,
       46,  103,   46,  108,  100,  104,   46,  109,  105,   46,
      131,  111,  107,  110,  112,   46,  119,  115,  120,   46,
       46,  121,  130,  122,  116,  117,  113,  114,   46,   46,
       46,  123,   46,   46,  118,  134,   46,  132,  136,   46,
       46,   46,  593,  138,   46,  133,   46,   46,   46,   46,
      139,  140,   46,  144,  137,   46,  135,  145,   46,   46,

      143,  142,  146,  147,  163,  141,  153,  149,   46,  154,
      148,  157,   46,  151,  161,  155,  152,  150,  159,  160,
       46,   46,  156,  164,  158,   46,   46,  162,   46,   46,
      166,   46,   46,   46,   46,   46,  165,   46,   46,   46,
       46,   46,  583,   46,  592,   46,  167,  584,   46,   46,
      180,  168,  171,  169,  172,  170,  179,  174,   46,  181,
      190,  182,  175,  184,  173,  192,  188,  189,  176,  183,
      185,   46,  177,  178,  186,  187,   46,  193,  194,  205,
       46,   46,   46,  195,   46,   46,   46,  226,  197,  196,
       46,   46,  591,  198,   46,   46,   46,   46,  590,  200,

      589,  206,   46,  208,   46,  126,  126,  199,  201,  203,
      215,  207,  209,  211,   46,  210,   46,  204,  216,  202,
      214,  212,  217,  219,   46,  220,  126,  127,  218,  128,
      128,  129,  129,  213,   46,  221,   46,  222,   46,   46,
       46,   46,   46,   46,   46,  223,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
      230,  225,   46,   46,  235,  224,  227,  228,  241,  244,
      238,  231,  242,  232,  229,  243,  234,  239,  233,  236,
      240,  245,   46,  237,  250,   46,  249,  248,   46,  246,
       46,  251,  252,   46,   46,  258,   46,   46,   46,   46,

      247,   46,  253,   46,   46,   46,   46,   46,   46,  254,
       46,  272,   46,  257,  275,   46,   46,   46,   46,  255,
      261,  256,  260,   46,  264,  266,   46,   46,  269,   46,
       46,  276,  259,  270,  262,  267,   46,  274,  263,  265,
       46,   46,  268,  273,  277,   46,  282,  271,  278,  281,
      283,   46,  279,   46,   46,  280,   46,   46,   46,   46,
       46,   46,   46,   46,  285,   46,  287,   46,   46,  286,
       46,   46,   46,  284,   46,   46,   46,   46,  294,  300,
      297,   46,  292,  296,   46,  288,  293,  290,  295,  291,
      289,  303,  298,   46,  299,   46,   46,  301,  311,   46,

      305,  312,  302,   46,  306,  307,  304,   46,  308,  309,
      310,   46,   46,  317,  313,   46,   46,  318,   46,   46,
      316,  315,  314,   46,   46,   46,   46,   46,   46,   46,
       46,   46,  323,   46,   46,   46,   46,   46,   46,  319,
      322,   46,  320,  321,  327,   46,   46,   46,   46,  328,
      330,  297,  325,  324,  329,  326,  333,   46,   46,  341,
      338,   46,   46,  331,  332,  334,  335,  336,  342,   46,
       46,   46,  339,  337,   46,  340,   46,   46,   46,  343,
       46,  345,  344,  354,   46,   46,  353,  352,   46,   46,
       46,  347,  350,   46,  358,  351,  359,   46,   46,   46,

       46,   46,   46,   46,  355,  356,  362,   46,   46,  363,
      357,   46,  365,   46,  360,   46,  361,   46,   46,  364,
      366,  369,  370,  372,  374,  376,   46,   46,   46,   46,
      367,   46,  378,  368,  371,   46,   46,  373,  380,   46,
       46,  375,   46,  382,   46,   46,   46,  377,   46,  379,
      394,   46,  381,   46,   46,   46,  384,  386,   46,   46,
       46,  383,  390,  385,   46,  387,  389,  392,   46,  388,
      391,  393,  397,  407,   46,  399,  395,  396,   46,   46,
      400,  402,   46,   46,  398,  404,   46,   46,   46,  401,
       46,   46,   46,   46,   46,   46,   46,   46,   46,  408,

      411,   46,  410,  413,   46,   46,   46,   46,   46,  418,
       46,   46,  409,  412,  419,  415,  420,  416,  421,   46,
       46,  423,  430,  414,  428,   46,  417,   46,  426,  422,
      424,   46,  433,  435,   46,   46,  429,  425,  434,  440,
       46,   46,  427,   46,  432,   46,  431,   46,   46,   46,
      436,   46,   46,   46,   46,  441,  437,   46,   46,  439,
       46,   46,   46,   46,  443,   46,  446,   46,   46,   46,
       46,  468,   46,  444,   46,  442,  455,   46,   46,  457,
      458,  464,  450,  453,  456,   46,   46,  454,  452,   46,
      451,  479,   46,  462,  459,  463,  460,  473,  461,  465,

       46,  466,  471,   46,  469,  478,   46,   46,  481,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
      480,   46,  556,   46,  588,   46,   46,  482,   46,   46,
       46,   46,  491,  557,   46,   46,  484,   46,   46,  483,
      487,  488,  489,  485,  486,  490,  502,  503,  506,  494,
      510,  504,  497,  508,  505,  509,  507,  495,  511,  514,
      516,   46,   46,  521,  523,   46,  522,  525,   46,   46,
       46,  587,  586,  585,  582,  581,  580,  579,  578,  577,
      576,  575,  574,  573,  572,  571,  570,  569,  534,  568,
      567,  566,  524,  529,  565,  564,  563,  562,  561,  535,

      538,   46,  560,  559,   46,   48,  558,   48,   49,   49,
       58,  553,  552,   58,  551,  550,  549,  548,  547,  546,
      545,  544,   46,  543,  542,   46,   46,  541,  540,  539,
      537,  536,   46,   46,  533,  532,  531,  530,  528,   46,
      527,  526,   46,   46,   46,   46,   46,  520,  519,  518,
      517,  515,   46,  513,  512,   46,   46,   46,  501,   46,
      500,  499,  498,  496,  493,  492,   46,   46,   46,  477,
      476,  475,   46,  474,   46,   46,   46,  472,  470,  467,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
      449,  448,  447,  445,   46,   46,  438,   46,   46,   46,

       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
      406,  405,  403,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,  349,
      348,   46,  346,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   47,   47,  125,   46,   57,   51,   50,
       47,   47,  600,    3,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,

      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600
    } ;

static const flex_int16_t yy_chk[1123] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   18,   23,
       18,   18,   20,   20,  598,   24,  596,   25,   29,   50,
       50,   51,   51,   52,   52,   30,  595,   32,   26,   23,
      594,   23,   44,   27,   25,   31,   24,   23,   28,   23,
       24,   25,   30,   34,   23,   26,   24,   23,   25,   26,
       27,   25,   29,   26,   25,   28,   44,   31,   32,   26,

       35,   27,   26,   27,   34,   31,   28,   36,   34,   28,
       31,   37,   28,   27,   60,   28,  550,   35,   38,  103,
      103,  593,   39,  592,   36,   35,   42,  550,   36,   53,
       40,   53,   53,   37,   54,   38,   54,   54,   36,   37,
       41,   37,   59,   39,   36,   37,   43,   39,   37,   61,
       60,   40,   38,   39,   40,   62,   42,   41,   42,   63,
       64,   42,   59,   43,   41,   41,   40,   40,   65,   66,
       67,   43,   68,   70,   41,   62,   69,   61,   63,   72,
       73,   76,  591,   64,   80,   61,   71,   74,   77,   75,
       65,   65,   79,   69,   63,   78,   62,   69,   81,   83,

       68,   67,   70,   70,   80,   66,   74,   71,   82,   74,
       70,   75,   84,   72,   78,   74,   73,   71,   76,   77,
       85,   87,   74,   81,   75,   86,   88,   79,   93,   95,
       83,   92,   94,   96,   97,   98,   82,   90,  100,   99,
      102,  105,  580,  106,  590,  104,   84,  580,  112,  141,
       93,   85,   87,   86,   88,   86,   92,   90,  107,   94,
      102,   94,   90,   96,   88,  104,  100,  100,   90,   95,
       97,  108,   90,   90,   98,   99,  109,  105,  106,  112,
      110,  111,  114,  107,  113,  115,  117,  141,  108,  107,
      120,  116,  589,  108,  122,  119,  118,  121,  588,  109,

      587,  113,  123,  115,  124,  126,  126,  108,  110,  111,
      120,  114,  116,  118,  131,  117,  133,  111,  121,  110,
      119,  118,  122,  123,  137,  124,  127,  127,  122,  128,
      128,  129,  129,  118,  139,  131,  140,  133,  142,  143,
      144,  145,  146,  147,  150,  137,  148,  149,  151,  152,
      156,  154,  153,  158,  155,  160,  164,  165,  171,  157,
      145,  140,  161,  162,  149,  139,  142,  143,  154,  156,
      152,  146,  154,  147,  144,  155,  148,  153,  147,  150,
      153,  157,  159,  151,  162,  166,  161,  160,  167,  158,
      168,  164,  165,  169,  170,  171,  172,  173,  175,  174,

      159,  176,  166,  177,  178,  179,  180,  181,  182,  167,
      185,  187,  187,  170,  191,  188,  189,  194,  197,  168,
      174,  169,  173,  192,  177,  178,  195,  193,  181,  198,
      196,  191,  172,  182,  175,  179,  199,  189,  176,  177,
      200,  201,  180,  188,  192,  203,  197,  185,  193,  196,
      198,  205,  194,  206,  208,  195,  209,  210,  211,  213,
      212,  214,  215,  216,  200,  217,  203,  219,  225,  201,
      220,  221,  218,  199,  222,  223,  224,  233,  210,  215,
      213,  234,  208,  212,  226,  205,  209,  206,  211,  206,
      205,  218,  214,  227,  214,  230,  231,  216,  225,  232,

      220,  226,  217,  235,  220,  221,  219,  236,  222,  223,
      224,  239,  237,  233,  227,  240,  241,  234,  242,  243,
      232,  231,  230,  245,  246,  250,  247,  251,  253,  257,
      252,  254,  240,  261,  258,  262,  263,  260,  265,  235,
      239,  264,  236,  237,  245,  266,  270,  271,  279,  246,
      250,  252,  242,  241,  247,  243,  254,  274,  277,  265,
      262,  278,  281,  251,  253,  257,  258,  260,  266,  280,
      283,  284,  263,  261,  285,  264,  286,  287,  288,  266,
      290,  271,  270,  281,  295,  291,  280,  279,  292,  296,
      298,  274,  277,  299,  286,  278,  287,  300,  303,  304,

      302,  309,  306,  310,  283,  284,  291,  312,  313,  292,
      285,  315,  296,  316,  288,  317,  290,  319,  321,  295,
      298,  302,  303,  306,  310,  313,  322,  323,  324,  325,
      299,  327,  316,  300,  304,  331,  326,  309,  319,  328,
      330,  312,  337,  322,  333,  329,  334,  315,  340,  317,
      335,  335,  321,  336,  343,  338,  324,  326,  341,  342,
      347,  323,  330,  325,  345,  327,  329,  333,  352,  328,
      331,  334,  338,  350,  350,  341,  336,  337,  353,  355,
      342,  345,  354,  356,  340,  347,  358,  359,  362,  343,
      360,  363,  364,  365,  369,  367,  375,  368,  376,  352,

      355,  383,  354,  358,  370,  373,  378,  379,  382,  364,
      384,  387,  353,  356,  365,  360,  367,  362,  368,  388,
      392,  370,  383,  359,  379,  393,  363,  385,  376,  369,
      373,  397,  387,  389,  389,  399,  382,  375,  388,  398,
      398,  400,  378,  401,  385,  402,  384,  404,  408,  409,
      392,  410,  412,  411,  415,  399,  393,  413,  416,  397,
      419,  418,  423,  432,  401,  434,  404,  424,  425,  433,
      428,  436,  436,  402,  437,  400,  413,  439,  443,  416,
      418,  432,  408,  411,  415,  450,  452,  412,  410,  453,
      409,  451,  451,  425,  419,  428,  423,  443,  424,  433,

      455,  434,  439,  456,  437,  450,  457,  458,  453,  459,
      461,  462,  463,  465,  469,  471,  473,  464,  484,  489,
      452,  487,  551,  485,  586,  480,  481,  455,  502,  490,
      488,  503,  465,  551,  504,  497,  457,  491,  495,  456,
      461,  462,  463,  458,  459,  464,  480,  481,  485,  469,
      490,  481,  473,  488,  484,  489,  487,  471,  491,  495,
      497,  506,  516,  502,  504,  523,  503,  510,  510,  524,
      529,  585,  584,  583,  579,  578,  577,  576,  575,  574,
      572,  570,  569,  568,  567,  566,  565,  564,  523,  563,
      562,  561,  506,  516,  560,  558,  557,  556,  555,  524,

      529,  601,  554,  553,  601,  602,  552,  602,  603,  603,
      604,  548,  547,  604,  546,  545,  544,  543,  542,  541,
      540,  539,  538,  537,  536,  535,  534,  532,  531,  530,
      526,  525,  522,  521,  520,  519,  518,  517,  515,  514,
      513,  512,  511,  509,  508,  507,  505,  501,  500,  499,
      498,  496,  494,  493,  492,  486,  483,  482,  479,  478,
      476,  475,  474,  472,  468,  467,  466,  460,  454,  449,
      448,  447,  446,  445,  444,  442,  441,  440,  438,  435,
      431,  430,  429,  427,  426,  422,  421,  420,  417,  414,
      407,  406,  405,  403,  396,  395,  394,  391,  390,  386,

      381,  380,  377,  374,  372,  371,  366,  361,  357,  351,
      349,  348,  346,  344,  339,  332,  320,  318,  314,  311,
      308,  307,  305,  301,  297,  294,  293,  289,  282,  276,
      275,  273,  272,  269,  268,  267,  259,  256,  255,  249,
      248,  244,  238,  229,  228,  207,  204,  202,  190,  186,
      184,  183,  163,  138,  136,  135,  134,  132,  130,  101,
       91,   89,   58,   49,   48,   45,   33,   22,   17,   14,
        8,    7,    3,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,

      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600,  600,  600,  600,  600,  600,  600,  600,  600,
      600,  600
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "parser/patterns.l"
#line 4 "parser/patterns.l"
#include "token.h"
#line 894 "parser/calc.lexer.c"
#line 895 "parser/calc.lexer.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 7 "parser/patterns.l"

#line 1114 "parser/calc.lexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 601 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1074 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 8 "parser/patterns.l"
{return CREATE;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 9 "parser/patterns.l"
{return TABLE;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 11 "parser/patterns.l"
{return DROP;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 13 "parser/patterns.l"
{return ALTER;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 14 "parser/patterns.l"
{return ADD;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 16 "parser/patterns.l"
{return ASSERTION;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 18 "parser/patterns.l"
{return VIEW;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 19 "parser/patterns.l"
{return AS;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 21 "parser/patterns.l"
{return INDEX;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 22 "parser/patterns.l"
{return ON;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 24 "parser/patterns.l"
{return TRIGGER;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 25 "parser/patterns.l"
{return REFERENCING;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 26 "parser/patterns.l"
{return BEFORE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 27 "parser/patterns.l"
{return UPDATE;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 28 "parser/patterns.l"
{return OF;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 29 "parser/patterns.l"
{return AFTER;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 30 "parser/patterns.l"
{return INSTEAD;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 31 "parser/patterns.l"
{return INSERT;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 32 "parser/patterns.l"
{return DELETE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 33 "parser/patterns.l"
{return OLD;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 34 "parser/patterns.l"
{return ROW;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 35 "parser/patterns.l"
{return NEW;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 36 "parser/patterns.l"
{return FOR;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 37 "parser/patterns.l"
{return EACH;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 38 "parser/patterns.l"
{return STATEMENT;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 39 "parser/patterns.l"
{return WHEN;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 40 "parser/patterns.l"
{return BEGINTOKEN;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 41 "parser/patterns.l"
{return END;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 43 "parser/patterns.l"
{return UNIQUE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 44 "parser/patterns.l"
{return PRIMARYKEY;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 45 "parser/patterns.l"
{return CHECK;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 46 "parser/patterns.l"
{return FOREIGNKEY;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 47 "parser/patterns.l"
{return REFERENCES;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 48 "parser/patterns.l"
{return NOT_DEFERRABLE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 49 "parser/patterns.l"
{return DEFERED_DEFERRABLE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 50 "parser/patterns.l"
{return IMMEDIATE_DEFERRABLE;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 51 "parser/patterns.l"
{return UPDATE_NULL;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 52 "parser/patterns.l"
{return UPDATE_CASCADE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 53 "parser/patterns.l"
{return DELETE_NULL;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 54 "parser/patterns.l"
{return DELETE_CASCADE;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 55 "parser/patterns.l"
{return CONSTRAINT;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 56 "parser/patterns.l"
{return DEFAULT;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 58 "parser/patterns.l"
{return STAR;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 59 "parser/patterns.l"
{return SUM;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 60 "parser/patterns.l"
{return AVG;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 61 "parser/patterns.l"
{return MIN;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 62 "parser/patterns.l"
{return MAX;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 63 "parser/patterns.l"
{return COUNT;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 64 "parser/patterns.l"
{return DISTINCT;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 66 "parser/patterns.l"
{return PLUS;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 67 "parser/patterns.l"
{return SUBTRACT;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 68 "parser/patterns.l"
{return DIVISION;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 69 "parser/patterns.l"
{return CONCATENATION;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 71 "parser/patterns.l"
{return CHAR;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 72 "parser/patterns.l"
{return VARCHAR;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 73 "parser/patterns.l"
{return BIT;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 74 "parser/patterns.l"
{return BITVARYING;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 75 "parser/patterns.l"
{return BOOLEAN;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 76 "parser/patterns.l"
{return INT;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 77 "parser/patterns.l"
{return INTEGER;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 78 "parser/patterns.l"
{return SHORTINT;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 79 "parser/patterns.l"
{return FLOAT;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 80 "parser/patterns.l"
{return REAL;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 81 "parser/patterns.l"
{return DOUBLEPRECISION;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 82 "parser/patterns.l"
{return DECIMAL;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 83 "parser/patterns.l"
{return NUMERIC;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 84 "parser/patterns.l"
{return DATE;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 85 "parser/patterns.l"
{return TIME;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 87 "parser/patterns.l"
{return LIKE;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 88 "parser/patterns.l"
{return IN;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 89 "parser/patterns.l"
{return ALL;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 90 "parser/patterns.l"
{return ANY;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 91 "parser/patterns.l"
{return IS;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 92 "parser/patterns.l"
{return EXISTS;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 94 "parser/patterns.l"
{return EQUAL;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 95 "parser/patterns.l"
{return NOTEQUAL;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 96 "parser/patterns.l"
{return LESS;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 97 "parser/patterns.l"
{return GREATER;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 98 "parser/patterns.l"
{return LESSEQUAL;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 99 "parser/patterns.l"
{return GREATEREQUAL;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 101 "parser/patterns.l"
{return AND;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 102 "parser/patterns.l"
{return OR;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 104 "parser/patterns.l"
{return DOT;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 106 "parser/patterns.l"
{return ELSEIF;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 107 "parser/patterns.l"
{return CALL;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 108 "parser/patterns.l"
{return THEN;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 109 "parser/patterns.l"
{return IF;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 110 "parser/patterns.l"
{return ELSE;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 111 "parser/patterns.l"
{return CURSOR;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 112 "parser/patterns.l"
{return DO;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 113 "parser/patterns.l"
{return RETURN;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 114 "parser/patterns.l"
{return SET;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 115 "parser/patterns.l"
{return OUT;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 116 "parser/patterns.l"
{return INOUT;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 117 "parser/patterns.l"
{return DECLARE;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 118 "parser/patterns.l"
{return PROCEDURE;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 119 "parser/patterns.l"
{return FUNCTION;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 120 "parser/patterns.l"
{return RETURNS;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 122 "parser/patterns.l"
{return FROM;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 123 "parser/patterns.l"
{return WHERE;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 125 "parser/patterns.l"
{return INSERTINTO;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 126 "parser/patterns.l"
{return VALUES;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 128 "parser/patterns.l"
{return START;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 129 "parser/patterns.l"
{return TRANSACTION;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 130 "parser/patterns.l"
{return COMMIT;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 131 "parser/patterns.l"
{return ROLLBACK;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 132 "parser/patterns.l"
{return SHOW;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 133 "parser/patterns.l"
{return TABLES;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 134 "parser/patterns.l"
{return ASSERTIONS;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 135 "parser/patterns.l"
{return VIEWS;}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 136 "parser/patterns.l"
{return INDEXS;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 137 "parser/patterns.l"
{return TRIGGERS;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 138 "parser/patterns.l"
{return FUNCTIONS;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 139 "parser/patterns.l"
{return PROCEDURES;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 140 "parser/patterns.l"
{return USER;}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 141 "parser/patterns.l"
{return PASSWORD;}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 142 "parser/patterns.l"
{return CONNECT;}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 143 "parser/patterns.l"
{return INITIALIZE;}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 144 "parser/patterns.l"
{return HALT;}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 146 "parser/patterns.l"
{return ASC;}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 147 "parser/patterns.l"
{return DESC;}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 148 "parser/patterns.l"
{return CROSS;}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 149 "parser/patterns.l"
{return JOIN;}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 150 "parser/patterns.l"
{return NATURAL;}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 151 "parser/patterns.l"
{return FULL;}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 152 "parser/patterns.l"
{return OUTER;}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 153 "parser/patterns.l"
{return LEFT;}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 154 "parser/patterns.l"
{return RIGHT;}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 155 "parser/patterns.l"
{return SELECT;}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 156 "parser/patterns.l"
{return GROUPBY;}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 157 "parser/patterns.l"
{return HAVING;}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 158 "parser/patterns.l"
{return ORDERBY;}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 159 "parser/patterns.l"
{return LIMIT;}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 160 "parser/patterns.l"
{return UNION;}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 161 "parser/patterns.l"
{return DIFFERENCE;}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 162 "parser/patterns.l"
{return INTERSECTION;}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 164 "parser/patterns.l"
{return INTVALUE;}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 165 "parser/patterns.l"
{return FLOATVALUE;}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 166 "parser/patterns.l"
{return STRINGVALUE;}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 167 "parser/patterns.l"
{return BOOLVALUE;}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 169 "parser/patterns.l"
{return SEMICOLON;}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 170 "parser/patterns.l"
{return LPAREN;}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 171 "parser/patterns.l"
{return RPAREN;}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 172 "parser/patterns.l"
{return COMMA;}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 173 "parser/patterns.l"
{return NOT;}
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 174 "parser/patterns.l"
{return NULLMARK;}
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 175 "parser/patterns.l"
{return ID;}
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 176 "parser/patterns.l"
{return PASSWORDS;}
	YY_BREAK
case 149:
/* rule 149 can match eol */
YY_RULE_SETUP
#line 177 "parser/patterns.l"
{/*ignore space*/}
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 178 "parser/patterns.l"
ECHO;
	YY_BREAK
#line 1922 "parser/calc.lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 601 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 601 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 600);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 178 "parser/patterns.l"

