#line 2 "parser/calc.lexer.c"

#line 4 "parser/calc.lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 131
#define YY_END_OF_BUFFER 132
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[519] =
    {   0,
        0,    0,  132,  131,  130,  129,  131,  131,  123,  124,
       43,   50,  125,   51,   83,   52,  118,  118,  122,   77,
       75,   78,  128,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  128,
      128,  131,  129,  120,    0,    0,  118,    0,    0,  118,
      118,   79,   76,   80,  128,  128,  128,  128,  128,    8,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  128,
      128,  128,   90,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  128,   87,   70,   73,  128,  128,  128,  128,
      128,  128,   15,  128,   10,   82,  128,  128,  128,  128,

      128,  128,  128,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  128,  128,  128,   53,  118,  118,  119,  119,
        5,  128,   71,  128,   81,   72,  128,   45,  128,  128,
       56,  128,  128,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  128,  128,  128,  128,  128,  128,  128,   28,
      128,  128,  128,   23,  128,  128,  128,  128,  128,   59,
      128,   47,   46,   22,  126,  128,  128,   20,    0,   93,
      128,  128,  128,  128,  128,  128,  128,   21,   92,  128,
      128,   44,  128,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  128,

      128,  128,   85,   54,  128,  128,  128,  128,  128,  128,
      128,   67,  128,  128,  128,  128,  128,  128,  128,    3,
       24,   88,  128,  128,  128,  128,   99,  128,  128,  128,
      128,  128,  128,   69,    0,  127,  128,    0,    0,  128,
      128,  128,   63,  128,  128,  128,  128,  107,  128,  128,
      128,   86,   68,  128,  128,  121,  128,  128,  115,  128,
      128,    7,   26,  128,   16,    4,  128,  128,   27,  128,
      128,   31,  128,  128,  128,   48,  128,  128,  128,  128,
      128,  128,  128,  128,  128,  128,  128,   62,  128,  128,
        9,   94,  128,  128,  128,    0,  128,    0,    0,  128,

      128,  128,  128,  128,  128,  128,  103,  128,    2,  128,
      128,  128,  128,  128,  128,  110,  100,  128,   13,  128,
      128,  105,  128,  128,    1,   89,  128,  128,  128,  128,
       19,  128,  128,   84,   74,  128,  128,  111,   18,  128,
      128,    0,  128,    0,    0,  128,  128,  128,  128,   91,
      128,  128,  128,  108,  128,  128,   29,   14,  102,  128,
      128,  128,   58,  117,  128,   65,   95,   42,  128,  128,
        0,  128,  128,    0,   17,   60,    0,   66,    0,    0,
      128,  128,  128,  128,   98,  128,  128,  128,  128,   11,
       55,  128,  128,  128,  128,   49,    0,    0,   97,    0,

        0,    0,    0,  116,    0,  128,  128,  106,   61,  128,
      128,  112,    6,  128,  128,  128,    0,    0,  113,    0,
        0,    0,    0,    0,   96,  128,  128,   25,  128,  109,
       57,   41,  128,    0,    0,    0,    0,    0,    0,    0,
      114,   33,  128,  128,    0,    0,   32,  101,    0,    0,
        0,   30,   12,  104,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   34,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   64,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   39,    0,
       37,    0,    0,    0,    0,    0,    0,    0,   40,   38,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   35,    0,   36,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    1,    1,    1,    1,    6,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   16,
       16,   16,   16,   16,   16,   16,   16,    1,   17,   18,
       19,   20,    1,    1,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   30,
        1,    1,    1,    1,   30,    1,   21,   22,   23,   24,

       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   30,    1,   46,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[47] =
    {   0,
        1,    1,    1,    2,    3,    4,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,    1,    1,    1,    1,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    1
    } ;

static yyconst flex_int16_t yy_base[523] =
    {   0,
        0,    0,  916,  917,  917,    0,  910,  908,  917,  917,
      917,  917,  917,  897,  917,  917,  899,   34,  917,   32,
      917,  892,   49,   51,   44,   73,   63,   83,  906,   66,
       60,   99,   92,   97,  105,  109,  112,  118,  115,  121,
       50,  863,    0,  917,  903,  901,   41,   43,   45,   53,
      142,  917,  917,  917,  902,   86,   59,  128,  137,   67,
      132,  144,  126,   58,  141,  158,  159,  160,  161,  163,
      165,  168,  170,  171,  172,  173,  174,  176,  177,  180,
      182,  183,  185,  901,  186,  900,  192,   70,  190,  197,
      198,  200,  899,  204,  210,  898,  212,  218,  213,  223,

      226,  225,  227,  230,  231,  232,  235,  233,  246,  239,
      237,  249,  241,  251,  252,  917,  231,  255,  265,  267,
      897,  268,  896,  274,  895,  894,  280,  893,  255,  281,
      282,  284,  285,  287,  288,  290,  292,  293,  291,  294,
      296,  300,  297,  303,  298,  315,  299,  302,  309,  892,
      304,  305,  332,  316,  335,  336,  338,  310,  341,  342,
      344,  891,  890,  889,  346,  343,  348,  888,  330,  887,
      351,  352,  353,  354,  357,  356,  360,  886,  885,  358,
      366,  884,  361,  368,  370,  373,  376,  374,  375,  379,
      380,  383,  385,  384,  387,  390,  394,  401,  405,  406,

      409,  410,  883,  882,  407,  412,  411,  413,  415,  416,
      419,  881,  418,  425,  422,  427,  429,  430,  438,  880,
      879,  433,  440,  441,  443,  444,  878,  445,  446,  448,
      453,  454,  457,  877,  856,  875,  456,  853,  841,  460,
      468,  467,  872,  463,  464,  471,  470,  871,  472,  473,
      474,  870,  869,  477,  478,  868,  482,  491,  867,  483,
      492,  493,  866,  496,  865,  864,  500,  502,  863,  503,
      505,  862,  507,  510,  511,  861,  509,  513,  514,  515,
      518,  520,  521,  525,  532,  526,  524,  860,  533,  535,
      534,  859,  538,  540,  541,  837,  539,  829,  836,  544,

      550,  551,  552,  558,  561,  565,  855,  563,  566,  568,
      570,  572,  576,  567,  577,  854,  853,  579,  852,  580,
      581,  851,  582,  583,  850,  849,  586,  587,  589,  595,
      848,  596,  599,  847,  846,  603,  605,  845,  607,  609,
      610,  822,  613,  822,  825,  616,  617,  619,  622,  620,
      623,  624,  626,  841,  627,  628,  840,  839,  838,  630,
      634,  635,  837,  836,  638,  835,  834,  833,  631,  637,
      800,  640,  641,  806,  830,  829,  807,  827,  790,  789,
      648,  667,  643,  651,  824,  645,  653,  657,  659,  661,
      823,  669,  674,  675,  678,  822,  787,  793,  676,  789,

      784,  796,  795,  815,  787,  679,  682,  813,  812,  680,
      683,  811,  684,  686,  681,  691,  789,  788,  808,  771,
      772,  806,  805,  782,  685,  688,  692,  802,  690,  801,
      800,  799,  694,  779,  756,  765,  778,  759,  758,  751,
      791,  790,  701,  697,  764,  763,  917,  917,  769,  765,
      764,  917,  784,  783,  752,  746,  752,  743,  742,  752,
      751,  754,  775,  774,  736,  740,  917,  683,  695,  745,
      739,  751,  730,  749,  728,  747,  917,  728,  734,  726,
      732,  731,  739,  729,  737,  727,  726,  736,  917,  735,
      917,  710,  730,  729,  749,  726,  725,  690,  917,  917,

      724,  715,  721,  713,  720,  718,  704,  713,  696,  704,
      705,  701,  678,  275,  917,   87,  917,  917,  730,  733,
      735,  739
    } ;

static yyconst flex_int16_t yy_def[523] =
    {   0,
      518,    1,  518,  518,  518,  519,  520,  521,  518,  518,
      518,  518,  518,  518,  518,  518,  519,  519,  518,  518,
      518,  518,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  518,  519,  518,  520,  521,  518,  518,  518,  519,
      519,  518,  518,  518,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,

      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  518,  518,  518,  518,  518,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  518,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,

      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  518,  522,  522,  518,  518,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  518,  522,  518,  518,  522,

      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  518,  522,  518,  518,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      518,  522,  522,  518,  522,  522,  518,  522,  518,  518,
      522,  522,  522,  522,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  518,  518,  522,  518,

      518,  518,  518,  522,  518,  522,  522,  522,  522,  522,
      522,  522,  522,  522,  522,  522,  518,  518,  522,  518,
      518,  518,  518,  518,  522,  522,  522,  522,  522,  522,
      522,  522,  522,  518,  518,  518,  518,  518,  518,  518,
      522,  522,  522,  522,  518,  518,  518,  518,  518,  518,
      518,  518,  522,  522,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,

      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,    0,  518,  518,
      518,  518
    } ;

static yyconst flex_int16_t yy_nxt[964] =
    {   0,
        4,    5,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   29,   30,   29,
       29,   31,   32,   33,   34,   35,   29,   36,   37,   38,
       39,   40,   41,   29,   29,   42,   49,   43,   50,   51,
       52,   53,   43,   43,   43,  117,  118,  119,  119,  120,
      120,   43,   43,   43,   65,   49,   43,   50,   50,   43,
       43,   66,   56,   43,   57,   62,   43,  115,   67,   63,
       58,   68,   59,   75,   69,   64,   43,   60,   87,   43,
       61,   84,  132,   70,   76,   43,   77,   71,  122,   85,

       43,   72,   43,   79,   86,  127,   78,   73,   43,  121,
       74,  517,   43,  162,   80,   43,   90,   81,   43,   88,
       82,   43,   93,   83,   43,   98,   91,   89,   94,   43,
       95,   43,   92,  100,   96,   43,  102,   97,  106,  103,
       43,  113,   99,  101,   43,  107,  108,   43,  110,  114,
      111,  104,  105,  112,   49,  109,   50,   51,  128,  123,
      125,   43,   43,   43,   43,  131,   43,  124,   43,  129,
      130,   43,  133,   43,   43,   43,   43,   43,  134,   43,
       43,  126,  135,   43,  139,   43,   43,  142,   43,   43,
      143,  136,  137,   43,  148,   43,  144,  150,  140,  138,

       43,   43,  141,   43,  151,  147,  145,   43,  152,  157,
      146,  149,  169,   43,  153,   43,   43,  155,  156,  154,
      158,   43,  161,  163,  159,  160,   43,  168,   43,   43,
       43,  166,  167,   43,   43,   43,   43,  165,   43,  164,
       43,  172,   43,  174,   43,  117,  117,  173,  175,   43,
      181,  170,   43,  183,   43,   43,  171,  177,   43,  184,
      190,  180,  176,  182,  179,  185,  186,  189,  178,  117,
      118,   43,  192,  191,  187,  194,  195,   43,  193,  119,
      119,  120,  120,   43,   43,   43,  188,   43,   43,  199,
       43,   43,  196,   43,   43,   43,   43,   43,  197,   43,

       43,   43,   43,   43,  198,   43,   43,   43,   43,  200,
      205,  210,   43,   43,  516,  202,  203,  215,   43,   43,
      212,  216,  206,  201,  204,  207,  209,  217,  213,  221,
      208,  214,  211,  222,  220,   43,  219,  218,   43,   43,
      226,   43,  223,  224,   43,   43,   43,   43,  235,   43,
      230,   43,  225,  238,   43,   43,   43,   43,  228,   43,
       43,   43,  229,   43,   43,  231,  233,  227,  234,   43,
      239,   43,  237,   43,  236,  242,   43,   43,   43,   43,
      232,  244,   43,   43,  241,  243,   43,   43,   43,  240,
       43,  246,  251,   43,  253,  247,  245,   43,  256,  258,

      248,  252,  255,  249,   43,  250,  254,  261,   43,   43,
       43,  257,   43,   43,   43,   43,   43,  259,   43,   43,
      263,   43,   43,  260,  264,   43,  262,  265,   43,  270,
       43,  266,   43,   43,  271,  274,   43,  272,  267,  269,
      273,   43,  268,   43,   43,  280,   43,   43,   43,   43,
      279,   43,  275,  278,  276,  277,   43,   43,  284,   43,
       43,  286,  281,   43,  282,  256,   43,   43,  283,  285,
       43,   43,  289,   43,   43,   43,   43,   43,  294,  287,
       43,   43,  288,  295,  290,   43,   43,  292,  301,  291,
      293,  302,  305,  297,   43,   43,   43,  308,  309,   43,

      303,  304,  300,   43,  311,   43,   43,  314,   43,  306,
       43,  307,   43,   43,   43,  310,   43,   43,   43,  315,
      317,   43,  312,   43,   43,  321,  319,   43,   43,   43,
      313,  316,  323,  325,  327,   43,   43,   43,   43,  318,
      320,   43,   43,   43,   43,  331,  322,   43,  324,  329,
      326,  334,  328,   43,   43,   43,  333,  330,  332,  336,
      340,   43,  335,  337,   43,  341,   43,  343,   43,   43,
       43,   43,  338,   43,  348,   43,  349,  339,  346,   43,
       43,  351,   43,   43,   43,   43,   43,  347,  355,   43,
       43,  350,   43,  352,  356,  353,  357,  360,   43,   43,

      358,  371,   43,  365,  354,  359,   43,  361,   43,  374,
       43,  367,   43,   43,  363,  369,   43,  366,  370,   43,
       43,  364,   43,   43,  362,   43,   43,   43,  368,   43,
       43,   43,  375,   43,   43,  378,  372,   43,   43,  373,
       43,   43,  398,   43,   43,  386,   43,  376,   43,  389,
      388,   43,  395,  381,   43,  384,   43,  387,  385,  383,
       43,  382,   43,  393,   43,  390,  394,  391,  392,  405,
       43,  404,   43,  407,  399,  408,  396,   43,   43,   43,
      406,   43,   43,   43,   43,   43,   43,   43,   43,   43,
      410,   43,  409,   43,   43,   43,  445,   43,  411,  412,

       43,  515,  413,  425,   43,  472,  426,  414,  415,  416,
      427,  429,  431,  501,  419,  433,  473,  474,  502,  428,
      432,  514,  430,  441,  444,  443,  442,  453,  475,  513,
      454,   43,  512,  511,   43,   45,  510,   45,   46,   46,
       55,  509,  508,   55,  507,  506,  505,  504,  503,  500,
      499,  498,  497,  496,  495,  494,  493,  492,  491,  490,
      489,  488,  487,  486,  485,  484,  483,  482,  481,  480,
      479,  478,  477,  476,  471,  470,  469,  468,  467,  466,
      465,  464,  463,  462,  461,  460,   43,   43,  459,  458,
      457,  456,  455,   43,   43,  452,  451,  450,  449,  448,

      447,  446,   43,   43,   43,   43,  440,  439,  438,  437,
      436,   43,  435,  434,   43,   43,   43,  424,   43,  423,
      422,  421,  420,  418,  417,   43,   43,   43,  403,  402,
       43,  401,   43,   43,  400,  397,   43,   43,   43,   43,
       43,   43,   43,   43,   43,  380,  379,  377,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,  345,
      344,  342,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,  299,  298,   43,  296,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   43,   43,   43,   43,   43,   43,   43,   43,   43,

       43,   43,   43,   43,   43,   43,   44,   44,  116,   43,
       54,   48,   47,   44,   44,  518,    3,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518
    } ;

static yyconst flex_int16_t yy_chk[964] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   18,   25,   18,   18,
       20,   20,   23,   41,   24,   47,   47,   48,   48,   49,
       49,   64,   57,   31,   25,   50,   27,   50,   50,   30,
       60,   25,   23,   88,   23,   24,   26,   41,   25,   24,
       23,   25,   23,   27,   25,   24,   28,   23,   31,   56,
       23,   30,   64,   26,   27,   33,   27,   26,   57,   30,

       34,   26,   32,   28,   30,   60,   27,   26,   35,   56,
       26,  516,   36,   88,   28,   37,   33,   28,   39,   32,
       28,   38,   34,   28,   40,   35,   33,   32,   34,   63,
       34,   58,   33,   36,   34,   61,   37,   34,   38,   37,
       59,   40,   35,   36,   65,   38,   38,   62,   39,   40,
       39,   37,   37,   39,   51,   38,   51,   51,   61,   58,
       59,   66,   67,   68,   69,   63,   70,   58,   71,   62,
       62,   72,   65,   73,   74,   75,   76,   77,   66,   78,
       79,   59,   66,   80,   68,   81,   82,   71,   83,   85,
       71,   67,   67,   89,   75,   87,   71,   77,   69,   67,

       90,   91,   70,   92,   78,   74,   72,   94,   79,   85,
       73,   76,   95,   95,   80,   97,   99,   82,   83,   81,
       85,   98,   87,   89,   85,   85,  100,   94,  102,  101,
      103,   92,   92,  104,  105,  106,  108,   91,  107,   90,
      111,   99,  110,  100,  113,  117,  117,   99,  100,  109,
      104,   97,  112,  106,  114,  115,   98,  101,  129,  107,
      111,  103,  100,  105,  102,  108,  109,  110,  101,  118,
      118,  122,  113,  112,  109,  114,  115,  124,  113,  119,
      119,  120,  120,  127,  130,  131,  109,  132,  133,  129,
      134,  135,  122,  136,  139,  137,  138,  140,  124,  141,

      143,  145,  147,  142,  127,  148,  144,  151,  152,  130,
      135,  139,  149,  158,  514,  132,  133,  143,  146,  154,
      141,  143,  136,  131,  134,  137,  138,  144,  142,  148,
      137,  142,  140,  149,  147,  153,  146,  145,  155,  156,
      154,  157,  151,  152,  159,  160,  166,  161,  165,  165,
      158,  167,  153,  169,  171,  172,  173,  174,  156,  176,
      175,  180,  157,  177,  183,  159,  160,  155,  161,  181,
      169,  184,  167,  185,  166,  173,  186,  188,  189,  187,
      159,  175,  190,  191,  172,  174,  192,  194,  193,  171,
      195,  177,  183,  196,  185,  180,  176,  197,  188,  190,

      180,  184,  187,  181,  198,  181,  186,  193,  199,  200,
      205,  189,  201,  202,  207,  206,  208,  191,  209,  210,
      195,  213,  211,  192,  195,  215,  194,  196,  214,  201,
      216,  197,  217,  218,  202,  207,  222,  205,  198,  200,
      206,  219,  199,  223,  224,  214,  225,  226,  228,  229,
      213,  230,  208,  211,  209,  210,  231,  232,  218,  237,
      233,  222,  215,  240,  216,  224,  244,  245,  217,  219,
      242,  241,  226,  247,  246,  249,  250,  251,  232,  223,
      254,  255,  225,  233,  228,  257,  260,  230,  241,  229,
      231,  242,  246,  237,  258,  261,  262,  250,  251,  264,

      244,  245,  240,  267,  255,  268,  270,  260,  271,  247,
      273,  249,  277,  274,  275,  254,  278,  279,  280,  261,
      264,  281,  257,  282,  283,  271,  268,  287,  284,  286,
      258,  262,  274,  277,  279,  285,  289,  291,  290,  267,
      270,  293,  297,  294,  295,  283,  273,  300,  275,  281,
      278,  286,  280,  301,  302,  303,  285,  282,  284,  289,
      294,  304,  287,  290,  305,  295,  308,  297,  306,  309,
      314,  310,  291,  311,  302,  312,  303,  293,  300,  313,
      315,  305,  318,  320,  321,  323,  324,  301,  310,  327,
      328,  304,  329,  306,  311,  308,  312,  315,  330,  332,

      313,  333,  333,  324,  309,  314,  336,  318,  337,  339,
      339,  328,  340,  341,  321,  330,  343,  327,  332,  346,
      347,  323,  348,  350,  320,  349,  351,  352,  329,  353,
      355,  356,  340,  360,  369,  343,  336,  361,  362,  337,
      370,  365,  372,  372,  373,  351,  383,  341,  386,  355,
      353,  381,  369,  346,  384,  349,  387,  352,  350,  348,
      388,  347,  389,  362,  390,  356,  365,  360,  361,  382,
      382,  381,  392,  384,  373,  386,  370,  393,  394,  399,
      383,  395,  406,  410,  415,  407,  411,  413,  425,  414,
      388,  426,  387,  429,  416,  427,  433,  433,  389,  390,

      444,  513,  392,  406,  443,  468,  407,  393,  394,  395,
      407,  411,  414,  498,  399,  416,  468,  469,  498,  410,
      415,  512,  413,  425,  429,  427,  426,  443,  469,  511,
      444,  519,  510,  509,  519,  520,  508,  520,  521,  521,
      522,  507,  506,  522,  505,  504,  503,  502,  501,  497,
      496,  495,  494,  493,  492,  490,  488,  487,  486,  485,
      484,  483,  482,  481,  480,  479,  478,  476,  475,  474,
      473,  472,  471,  470,  466,  465,  464,  463,  462,  461,
      460,  459,  458,  457,  456,  455,  454,  453,  451,  450,
      449,  446,  445,  442,  441,  440,  439,  438,  437,  436,

      435,  434,  432,  431,  430,  428,  424,  423,  422,  421,
      420,  419,  418,  417,  412,  409,  408,  405,  404,  403,
      402,  401,  400,  398,  397,  396,  391,  385,  380,  379,
      378,  377,  376,  375,  374,  371,  368,  367,  366,  364,
      363,  359,  358,  357,  354,  345,  344,  342,  338,  335,
      334,  331,  326,  325,  322,  319,  317,  316,  307,  299,
      298,  296,  292,  288,  276,  272,  269,  266,  265,  263,
      259,  256,  253,  252,  248,  243,  239,  238,  236,  235,
      234,  227,  221,  220,  212,  204,  203,  182,  179,  178,
      170,  168,  164,  163,  162,  150,  128,  126,  125,  123,

      121,   96,   93,   86,   84,   55,   46,   45,   42,   29,
       22,   17,   14,    8,    7,    3,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518,  518,  518,  518,  518,  518,  518,  518,
      518,  518,  518
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "parser/patterns.l"
#line 4 "parser/patterns.l"
#include "token.h"
#line 840 "parser/calc.lexer.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 7 "parser/patterns.l"

#line 1024 "parser/calc.lexer.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 519 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 917 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 8 "parser/patterns.l"
{return CREATE;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 9 "parser/patterns.l"
{return TABLE;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 11 "parser/patterns.l"
{return DROP;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 13 "parser/patterns.l"
{return ALTER;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 14 "parser/patterns.l"
{return ADD;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 16 "parser/patterns.l"
{return ASSERTION;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 18 "parser/patterns.l"
{return VIEW;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 19 "parser/patterns.l"
{return AS;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 21 "parser/patterns.l"
{return INDEX;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 22 "parser/patterns.l"
{return ON;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 24 "parser/patterns.l"
{return TRIGGER;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 25 "parser/patterns.l"
{return REFERENCING;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 26 "parser/patterns.l"
{return BEFORE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 27 "parser/patterns.l"
{return UPDATE;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 28 "parser/patterns.l"
{return OF;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 29 "parser/patterns.l"
{return AFTER;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 30 "parser/patterns.l"
{return INSTEAD;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 31 "parser/patterns.l"
{return INSERT;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 32 "parser/patterns.l"
{return DELETE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 33 "parser/patterns.l"
{return OLD;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 34 "parser/patterns.l"
{return ROW;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 35 "parser/patterns.l"
{return NEW;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 36 "parser/patterns.l"
{return FOR;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 37 "parser/patterns.l"
{return EACH;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 38 "parser/patterns.l"
{return STATEMENT;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 39 "parser/patterns.l"
{return WHEN;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 40 "parser/patterns.l"
{return BEGINTOKEN;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 41 "parser/patterns.l"
{return END;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 43 "parser/patterns.l"
{return UNIQUE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 44 "parser/patterns.l"
{return PRIMARYKEY;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 45 "parser/patterns.l"
{return CHECK;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 46 "parser/patterns.l"
{return FOREIGNKEY;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 47 "parser/patterns.l"
{return REFERENCES;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 48 "parser/patterns.l"
{return NOT_DEFERRABLE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 49 "parser/patterns.l"
{return DEFERED_DEFERRABLE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 50 "parser/patterns.l"
{return IMMEDIATE_DEFERRABLE;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 51 "parser/patterns.l"
{return UPDATE_NULL;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 52 "parser/patterns.l"
{return UPDATE_CASCADE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 53 "parser/patterns.l"
{return DELETE_NULL;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 54 "parser/patterns.l"
{return DELETE_CASCADE;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 55 "parser/patterns.l"
{return CONSTRAINT;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 56 "parser/patterns.l"
{return DEFAULT;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 58 "parser/patterns.l"
{return STAR;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 59 "parser/patterns.l"
{return SUM;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 60 "parser/patterns.l"
{return AVG;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 61 "parser/patterns.l"
{return MIN;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 62 "parser/patterns.l"
{return MAX;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 63 "parser/patterns.l"
{return COUNT;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 64 "parser/patterns.l"
{return DISTINCT;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 66 "parser/patterns.l"
{return PLUS;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 67 "parser/patterns.l"
{return SUBTRACT;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 68 "parser/patterns.l"
{return DIVISION;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 69 "parser/patterns.l"
{return CONCATENATION;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 71 "parser/patterns.l"
{return CHAR;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 72 "parser/patterns.l"
{return VARCHAR;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 73 "parser/patterns.l"
{return BIT;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 74 "parser/patterns.l"
{return BITVARYING;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 75 "parser/patterns.l"
{return BOOLEAN;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 76 "parser/patterns.l"
{return INT;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 77 "parser/patterns.l"
{return INTEGER;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 78 "parser/patterns.l"
{return SHORTINT;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 79 "parser/patterns.l"
{return FLOAT;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 80 "parser/patterns.l"
{return REAL;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 81 "parser/patterns.l"
{return DOUBLEPRECISION;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 82 "parser/patterns.l"
{return DECIMAL;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 83 "parser/patterns.l"
{return NUMERIC;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 84 "parser/patterns.l"
{return DATE;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 85 "parser/patterns.l"
{return TIME;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 87 "parser/patterns.l"
{return LIKE;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 88 "parser/patterns.l"
{return IN;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 89 "parser/patterns.l"
{return ALL;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 90 "parser/patterns.l"
{return ANY;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 91 "parser/patterns.l"
{return IS;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 92 "parser/patterns.l"
{return EXISTS;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 94 "parser/patterns.l"
{return EQUAL;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 95 "parser/patterns.l"
{return NOTEQUAL;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 96 "parser/patterns.l"
{return LESS;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 97 "parser/patterns.l"
{return GREATER;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 98 "parser/patterns.l"
{return LESSEQUAL;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 99 "parser/patterns.l"
{return GREATEREQUAL;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 101 "parser/patterns.l"
{return AND;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 102 "parser/patterns.l"
{return OR;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 104 "parser/patterns.l"
{return DOT;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 106 "parser/patterns.l"
{return ELSEIF;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 107 "parser/patterns.l"
{return CALL;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 108 "parser/patterns.l"
{return THEN;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 109 "parser/patterns.l"
{return IF;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 110 "parser/patterns.l"
{return ELSE;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 111 "parser/patterns.l"
{return CURSOR;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 112 "parser/patterns.l"
{return DO;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 113 "parser/patterns.l"
{return RETURN;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 114 "parser/patterns.l"
{return SET;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 115 "parser/patterns.l"
{return OUT;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 116 "parser/patterns.l"
{return INOUT;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 117 "parser/patterns.l"
{return DECLARE;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 118 "parser/patterns.l"
{return PROCEDURE;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 119 "parser/patterns.l"
{return FUNCTION;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 120 "parser/patterns.l"
{return RETURNS;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 122 "parser/patterns.l"
{return FROM;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 123 "parser/patterns.l"
{return WHERE;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 125 "parser/patterns.l"
{return INSERTINTO;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 126 "parser/patterns.l"
{return VALUES;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 128 "parser/patterns.l"
{return START;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 129 "parser/patterns.l"
{return TRANSACTION;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 130 "parser/patterns.l"
{return COMMIT;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 131 "parser/patterns.l"
{return ROLLBACK;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 132 "parser/patterns.l"
{return SHOW;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 133 "parser/patterns.l"
{return TABLES;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 134 "parser/patterns.l"
{return ASSERTIONS;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 135 "parser/patterns.l"
{return VIEWS;}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 136 "parser/patterns.l"
{return INDEXS;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 137 "parser/patterns.l"
{return TRIGGERS;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 138 "parser/patterns.l"
{return FUNCTIONS;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 139 "parser/patterns.l"
{return PROCEDURES;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 140 "parser/patterns.l"
{return USER;}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 141 "parser/patterns.l"
{return PASSWORD;}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 142 "parser/patterns.l"
{return CONNECT;}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 144 "parser/patterns.l"
{return INTVALUE;}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 145 "parser/patterns.l"
{return FLOATVALUE;}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 146 "parser/patterns.l"
{return STRINGVALUE;}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 147 "parser/patterns.l"
{return BOOLVALUE;}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 149 "parser/patterns.l"
{return SEMICOLON;}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 150 "parser/patterns.l"
{return LPAREN;}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 151 "parser/patterns.l"
{return RPAREN;}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 152 "parser/patterns.l"
{return COMMA;}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 153 "parser/patterns.l"
{return NOT;}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 154 "parser/patterns.l"
{return NULLMARK;}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 155 "parser/patterns.l"
{return ID;}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 156 "parser/patterns.l"
{return PASSWORDS;}
	YY_BREAK
case 130:
/* rule 130 can match eol */
YY_RULE_SETUP
#line 157 "parser/patterns.l"
{/*ignore space*/}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 158 "parser/patterns.l"
ECHO;
	YY_BREAK
#line 1763 "parser/calc.lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 519 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 519 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 518);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 158 "parser/patterns.l"


