#line 1 "parser/calc.lexer.c"

#line 3 "parser/calc.lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 148
#define YY_END_OF_BUFFER 149
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[591] =
    {   0,
        0,    0,  149,  148,  147,  146,  148,  148,  140,  141,
       43,   50,  142,   51,   83,   52,  135,  135,  139,   77,
       75,   78,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  148,  146,  137,    0,    0,  135,
        0,    0,  135,  135,   79,   76,   80,  145,  145,  145,
      145,  145,    8,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,   90,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,   87,   70,
       73,  145,  145,  145,  145,  145,  145,  145,  145,  145,

       15,  145,   10,   82,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,   53,  135,  135,  136,  136,    5,
      145,   71,  145,   81,   72,  118,  145,   45,  145,  145,
       56,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,   28,  145,  145,  145,   23,  145,  145,  145,
      145,  145,  145,  145,  145,   59,  145,  145,  145,  145,
       47,   46,  145,   22,  143,  145,  145,   20,    0,  145,
       93,  145,  145,  145,  145,  145,  145,  145,  145,   21,

      145,   92,  145,  145,   44,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,   85,   54,  145,  145,  145,
      145,  145,  145,  145,  145,   67,  145,  145,  145,  145,
      145,  119,  145,  145,  145,    3,   24,   88,  145,  145,
      145,  145,   99,  123,  145,  145,  145,  145,  145,  145,
      145,  145,  121,  125,   69,  145,  145,    0,  144,  145,
        0,    0,  145,  145,  145,  145,  145,   63,  145,  145,
      145,  145,  145,  145,  107,  145,  145,  145,   86,   68,
      145,  145,  138,  145,  145,  145,  115,  145,  145,    7,

       26,  145,   16,    4,  145,  145,   27,  145,  145,   31,
      145,  145,  145,   48,  145,  120,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,   62,  145,  145,
      145,  145,    9,   94,  145,  145,  145,  145,  131,  145,
        0,  145,    0,    0,  145,  124,  145,  145,  145,  145,
      145,  126,  145,  145,  145,  103,  145,    2,  145,  145,
      132,  145,  145,  145,  145,  110,  100,  145,   13,  145,
      145,  105,  145,  145,    1,   89,  145,  145,  145,  145,
       19,  145,  145,  145,   84,   74,  145,  145,    0,  129,
      111,   18,  145,  145,  145,  145,    0,  145,    0,    0,

        0,  145,  145,  145,  145,   91,  145,  127,  145,  145,
      108,  145,  145,   29,   14,  102,  145,  145,  145,   58,
      117,  145,   65,   95,   42,  145,  145,  145,    0,  145,
      145,    0,    0,   17,   60,  145,  122,    0,   66,    0,
        0,    0,  145,  145,  145,  145,   98,  145,  145,  145,
      145,   11,   55,  145,  145,  145,  145,  145,   49,    0,
        0,   97,  128,    0,  145,    0,    0,    0,  130,  116,
        0,  145,  145,  106,   61,  145,  145,  112,    6,  145,
      145,  145,  145,    0,    0,  113,    0,  145,    0,    0,
        0,    0,   96,  145,  145,   25,  145,  109,   57,   41,

      145,  133,    0,    0,    0,  145,    0,    0,    0,    0,
      114,   33,  145,  145,    0,    0,   32,  101,  145,    0,
        0,    0,   30,   12,  104,    0,    0,  134,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   34,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   64,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       39,    0,   37,    0,    0,    0,    0,    0,    0,    0,
       40,   38,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   35,    0,   36,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    1,    1,    1,    1,    6,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   16,
       16,   16,   16,   16,   16,   16,   16,    1,   17,   18,
       19,   20,    1,    1,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
        1,    1,    1,    1,   46,    1,   21,   22,   23,   24,

       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   46,    1,   47,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[48] =
    {   0,
        1,    1,    1,    2,    3,    4,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,    1,    1,    1,    1,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    1
    } ;

static const flex_int16_t yy_base[595] =
    {   0,
        0,    0, 1052, 1053, 1053,    0, 1046, 1044, 1053, 1053,
     1053, 1053, 1053, 1033, 1053, 1053, 1035,   35, 1053,   33,
     1053, 1028,   45,   51,   53,   64,   69,   74,   54,   61,
       71,   63, 1042,   79,   96,  103,  107,  114,  118,  126,
      136,  122,  142,   68,  998,    0, 1053, 1039, 1037,   44,
       46,   48,  116,  121, 1053, 1053, 1053, 1038,  138,  110,
      145,  151,  155,  156,  164,  165,  166,  168,  172,  169,
      182,  175,  176,  183,  185,  177,  184,  191,  188,  180,
      194,  204,  195,  208,  216,  221,  217,  222, 1037,  230,
     1036,  227,  224,  228,  229,  233,  231,  225,  234,  243,

     1035,  236,  116,  238,  237,  239,  253,  259,  245,  254,
      262,  244,  277,  279,  283,  285,  280,  286,  287,  296,
      289,  291,  292,  297, 1053,  229,  288,  293,  303, 1034,
      307, 1033,  317, 1032, 1031, 1030,  320, 1029,  302,  321,
      288,  322,  324,  327,  329,  330,  332,  334,  336,  331,
      335,  337,  340,  339,  342,  354,  347,  343,  357,  344,
      371,  351, 1028,  345,  349,  374,  377,  378,  355,  381,
      382,  385,  387,  386,  388,  390,  392,  389,  393,  396,
     1027, 1026,  394, 1025,  402,  399,  397, 1024,  383,  405,
      412,  404,  406,  413,  415,  416,  417,  428,  429, 1023,

      430, 1022,  434,  436, 1021,  438,  441,  440,  444,  442,
      446,  445,  447,  448,  449,  450,  453,  455,  456,  459,
      460,  462,  458,  463,  477, 1020, 1019,  475,  479,  484,
      481,  483,  487,  491,  497, 1018,  495,  499,  500,  501,
      503, 1017,  506,  507,  508, 1016, 1015,  509,  510,  512,
      511,  513, 1014, 1013,  514,  520,  515,  518,  521,  522,
      530,  525, 1012, 1011, 1010,  529,  540,  989, 1008,  541,
      986,  974,  542,  543,  531,  544,  560, 1005,  549,  553,
      554,  555,  563,  562, 1004,  564,  567,  568, 1003, 1002,
      566,  569, 1001,  572,  571,  578, 1000,  584,  579,  580,

      999,  585,  998,  997,  586,  591,  996,  593,  594,  995,
      595,  597,  596,  994,  599,  993,  604,  607,  609,  613,
      610,  618,  617,  619,  621,  623,  625,  992,  629,  628,
      633,  634,  626,  991,  635,  637,  646,  640,  990,  647,
      968,  648,  960,  967,  656,  986,  650,  636,  658,  659,
      662,  985,  665,  663,  666,  984,  668,  669,  672,  674,
      983,  677,  679,  676,  684,  982,  981,  683,  980,  685,
      686,  979,  687,  688,  978,  977,  690,  693,  694,  696,
      976,  703,  702,  707,  975,  974,  709,  710,  955,  972,
      971,  720,  712,  715,  717,  722,  948,  725,  948,  951,

      949,  727,  728,  729,  733,  735,  734,  966,  737,  731,
      965,  736,  740,  964,  963,  962,  742,  746,  743,  961,
      960,  747,  959,  958,  957,  757,  748,  745,  924,  759,
      754,  914,  929,  953,  952,  760,  951,  929,  949,  912,
      911,  905,  751,  765,  756,  773,  945,  762,  780,  782,
      783,  785,  944,  787,  788,  791,  786,  794,  943,  908,
      914,  793, 1053,  910,  795,  905,  917,  916, 1053,  936,
      908,  801,  802,  934,  933,  796,  799,  932,  798,  803,
      800,  804,  808,  910,  909,  929,  892,  805,  893,  927,
      926,  903,  806,  807,  809,  923,  815,  922,  921,  920,

      811,  919,  899,  876,  885,  834,  898,  879,  878,  871,
      911,  910,  835,  837,  884,  883, 1053, 1053,  838,  889,
      885,  884, 1053,  904,  903,  872,  866,  900,  871,  862,
      861,  871,  870,  873,  894,  893,  855,  859, 1053,   93,
      821,  864,  858,  870,  849,  868,  847,  866, 1053,  847,
      852,  844,  846,  843,  851,  838,  845,  835,  834,  844,
     1053,  843, 1053,  818,  837,  836,  856,  833,  832,  823,
     1053, 1053,  831,  821,  827,  818,  824,  823,  763,  215,
      144,   94,   96,   49,   42,   16, 1053,   29, 1053, 1053,
      871,  874,  876,  880

    } ;

static const flex_int16_t yy_def[595] =
    {   0,
      590,    1,  590,  590,  590,  591,  592,  593,  590,  590,
      590,  590,  590,  590,  590,  590,  591,  591,  590,  590,
      590,  590,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  590,  591,  590,  592,  593,  590,
      590,  590,  591,  591,  590,  590,  590,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,

      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  590,  590,  590,  590,  590,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  590,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,

      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  590,  594,  594,
      590,  590,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,

      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      590,  594,  590,  590,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  590,  594,
      594,  594,  594,  594,  594,  594,  590,  594,  590,  590,

      590,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  590,  594,
      594,  590,  590,  594,  594,  594,  594,  590,  594,  590,
      590,  590,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  594,  594,  594,  594,  594,  594,  590,
      590,  594,  590,  590,  594,  590,  590,  590,  590,  594,
      590,  594,  594,  594,  594,  594,  594,  594,  594,  594,
      594,  594,  594,  590,  590,  594,  590,  594,  590,  590,
      590,  590,  594,  594,  594,  594,  594,  594,  594,  594,

      594,  594,  590,  590,  590,  594,  590,  590,  590,  590,
      594,  594,  594,  594,  590,  590,  590,  590,  594,  590,
      590,  590,  590,  594,  594,  590,  590,  594,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,    0,
      590,  590,  590,  590

    } ;

static const flex_int16_t yy_nxt[1101] =
    {   0,
        4,    5,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   33,   39,   40,   41,
       42,   43,   44,   33,   33,   33,   45,   52,   46,   53,
       54,   55,   56,  589,   46,  588,   46,   46,  126,  127,
      128,  128,  129,  129,   46,  587,   46,   46,   59,  586,
       60,   46,   46,   68,   46,   65,   61,   46,   62,   66,
       69,   88,   46,   63,   73,   67,   64,   70,   74,   78,
       71,   87,   75,   72,   82,  124,   89,   92,   76,   46,

       79,   77,   80,   93,   90,   83,   46,   94,   84,   91,
       46,   85,   81,   46,   86,  544,   95,   46,  189,   46,
      585,   46,  584,   97,   96,   46,  545,   98,   52,   46,
       53,   53,  101,   52,  106,   53,   54,   99,  102,   46,
      103,   46,  108,  100,  104,   46,  109,  105,   46,  131,
      111,  107,  110,  112,   46,  119,  115,  120,   46,   46,
      121,  130,  122,  116,  117,  113,  114,   46,   46,   46,
      123,   46,   46,  118,  134,   46,  132,  136,   46,   46,
       46,  583,  138,   46,  133,   46,   46,   46,   46,  139,
      140,   46,  144,  137,   46,  135,  145,   46,   46,  143,

      142,  146,  147,  163,  141,  153,  149,   46,  154,  148,
      157,   46,  151,  161,  155,  152,  150,  159,  160,   46,
       46,  156,  164,  158,   46,   46,  162,   46,   46,  166,
       46,   46,   46,   46,   46,  165,   46,   46,  582,   46,
       46,   46,   46,  126,  126,  167,   46,   46,   46,  178,
      168,  171,  169,  173,  170,  177,   46,   46,  179,  188,
      180,  190,   46,  172,  174,   46,  182,  184,  175,  176,
      183,  198,  181,  185,  186,  187,  191,  192,  203,  195,
       46,  193,   46,   46,  196,  199,   46,  194,   46,   46,
       46,   46,   46,  201,   46,   46,  200,  204,  197,   46,

       46,  202,  126,  127,  206,   46,  209,  128,  128,  207,
       46,  205,  208,  214,  210,  212,  217,  129,  129,  213,
       46,  218,  215,   46,   46,   46,  211,   46,  216,  224,
       46,  219,   46,   46,   46,   46,  222,   46,   46,   46,
       46,  220,   46,   46,  221,   46,   46,   46,   46,  223,
       46,  228,   46,  225,   46,  226,  233,   46,   46,  239,
       46,  236,  229,  240,  227,  230,  241,  232,  237,  234,
      231,  238,  243,  235,   46,  248,  242,   46,  245,  246,
       46,   46,  244,  249,   46,   46,  254,  250,   46,   46,
       46,   46,   46,   46,  251,   46,   46,   46,  247,   46,

       46,  252,   46,  255,  268,   46,  271,   46,   46,   46,
      253,  258,  260,  257,  262,   46,   46,  265,   46,   46,
       46,  270,  256,  272,  266,  263,  259,  261,  264,  273,
      269,   46,   46,   46,  267,  277,  274,   46,  276,   46,
      279,   46,  275,   46,   46,   46,  278,   46,   46,   46,
       46,   46,   46,   46,  283,  281,   46,  280,   46,   46,
      282,   46,   46,   46,  290,   46,   46,  296,  292,  288,
      293,  284,  299,  286,  289,  287,  285,  291,   46,  294,
       46,  295,   46,  308,   46,  297,   46,   46,  301,  298,
       46,  307,  302,  303,   46,  300,  304,  305,   46,  306,

       46,  309,   46,   46,   46,  310,   46,  311,  312,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,  319,
      313,   46,  314,   46,   46,   46,  315,  318,   46,  316,
      323,  317,   46,   46,   46,  324,  293,  326,  321,  325,
      320,  329,  322,   46,   46,   46,   46,   46,  332,  327,
      328,  337,   46,  330,  336,  331,   46,   46,   46,  335,
      334,  333,  338,   46,  348,   46,   46,   46,  339,   46,
       46,   46,   46,  347,   46,   46,  353,  340,  342,  345,
      346,   46,   46,   46,  349,  354,  350,   46,   46,   46,
      351,  357,  358,  352,   46,  360,   46,   46,   46,   46,

       46,  355,   46,  356,  359,  361,  365,   46,  364,  367,
       46,  362,   46,   46,  371,  369,   46,  363,  366,  373,
       46,   46,   46,  375,   46,  368,   46,  377,   46,   46,
      370,   46,   46,  374,  372,  389,   46,   46,   46,   46,
       46,  376,  381,   46,  379,  384,  378,  380,  385,   46,
       46,   46,  383,   46,  382,  387,  388,  393,  401,   46,
      390,   46,   46,  386,  391,   46,   46,  396,   46,   46,
      394,   46,   46,  403,  392,   46,  398,   46,  395,   46,
       46,  404,   46,  405,  402,  407,   46,   46,   46,   46,
       46,   46,  412,   46,  409,  406,   46,   46,  413,   46,

      410,  414,  408,  415,  417,   46,   46,  411,  422,  429,
       46,  418,   46,   46,  416,   46,  426,  424,   46,  420,
       46,  423,  433,   46,  428,   46,  421,  427,   46,  419,
       46,   46,   46,  425,   46,  434,   46,   46,   46,   46,
       46,  436,  430,   46,  431,   46,   46,  439,   46,   46,
       46,   46,  435,  437,   46,  450,  448,   46,  451,   46,
       46,  461,   46,   46,  443,   46,  446,  471,   46,  445,
      449,  455,  444,  447,  470,  456,   46,  452,  457,  453,
      454,  458,  465,   46,  459,   46,   46,  462,   46,   46,
       46,   46,  474,  472,   46,  473,   46,   46,   46,   46,

      581,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,  515,   46,  476,  483,  482,   46,  475,
      479,  480,  477,  478,  481,  493,  494,  497,  501,  499,
      495,  486,  502,  506,  488,  496,  498,   46,   46,  500,
       46,   46,  513,  546,  511,  512,  573,  580,  579,  514,
      578,  574,  577,  576,  547,  575,  572,  571,  570,  569,
      568,  524,  567,  566,  565,  564,  563,  562,  519,  561,
      525,  528,   46,  560,  559,   46,   48,  558,   48,   49,
       49,   58,  557,  556,   58,  555,  554,  553,  552,  551,
      550,  549,  548,  543,  542,  541,  540,  539,  538,  537,

      536,  535,  534,   46,  533,  532,   46,   46,  531,  530,
      529,  527,  526,   46,   46,  523,  522,  521,  520,  518,
      517,  516,   46,   46,   46,   46,   46,  510,  509,  508,
      507,  505,   46,  504,  503,   46,   46,   46,  492,   46,
      491,  490,  489,  487,  485,  484,   46,   46,   46,  469,
      468,  467,   46,  466,   46,   46,   46,  464,  463,  460,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
      442,  441,  440,  438,   46,   46,  432,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
      400,  399,  397,   46,   46,   46,   46,   46,   46,   46,

       46,   46,   46,   46,   46,   46,   46,   46,   46,  344,
      343,   46,  341,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   47,   47,  125,   46,   57,   51,   50,   47,
       47,  590,    3,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590

    } ;

static const flex_int16_t yy_chk[1101] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,   18,   23,   18,
       18,   20,   20,  588,   24,  586,   25,   29,   50,   50,
       51,   51,   52,   52,   30,  585,   32,   26,   23,  584,
       23,   44,   27,   25,   31,   24,   23,   28,   23,   24,
       25,   30,   34,   23,   26,   24,   23,   25,   26,   27,
       25,   29,   26,   25,   28,   44,   31,   32,   26,   35,

       27,   26,   27,   34,   31,   28,   36,   34,   28,   31,
       37,   28,   27,   60,   28,  540,   35,   38,  103,  103,
      583,   39,  582,   36,   35,   42,  540,   36,   53,   40,
       53,   53,   37,   54,   38,   54,   54,   36,   37,   41,
       37,   59,   39,   36,   37,   43,   39,   37,   61,   60,
       40,   38,   39,   40,   62,   42,   41,   42,   63,   64,
       42,   59,   43,   41,   41,   40,   40,   65,   66,   67,
       43,   68,   70,   41,   62,   69,   61,   63,   72,   73,
       76,  581,   64,   80,   61,   71,   74,   77,   75,   65,
       65,   79,   69,   63,   78,   62,   69,   81,   83,   68,

       67,   70,   70,   80,   66,   74,   71,   82,   74,   70,
       75,   84,   72,   78,   74,   73,   71,   76,   77,   85,
       87,   74,   81,   75,   86,   88,   79,   93,   98,   83,
       92,   94,   95,   90,   97,   82,   96,   99,  580,  102,
      105,  104,  106,  126,  126,   84,  100,  112,  109,   93,
       85,   87,   86,   90,   86,   92,  107,  110,   94,  102,
       94,  104,  108,   88,   90,  111,   96,   98,   90,   90,
       97,  109,   95,   99,  100,  100,  105,  106,  112,  108,
      113,  107,  114,  117,  108,  110,  115,  107,  116,  118,
      119,  141,  121,  111,  122,  123,  110,  113,  108,  120,

      124,  111,  127,  127,  115,  139,  118,  128,  128,  116,
      131,  114,  117,  121,  118,  119,  123,  129,  129,  120,
      133,  124,  122,  137,  140,  142,  118,  143,  122,  141,
      144,  131,  145,  146,  150,  147,  139,  148,  151,  149,
      152,  133,  154,  153,  137,  155,  158,  160,  164,  140,
      157,  145,  165,  142,  162,  143,  149,  156,  169,  154,
      159,  152,  146,  154,  144,  147,  155,  148,  153,  150,
      147,  153,  157,  151,  161,  162,  156,  166,  159,  160,
      167,  168,  158,  164,  170,  171,  169,  165,  172,  174,
      173,  175,  178,  176,  166,  177,  179,  183,  161,  180,

      187,  167,  186,  170,  185,  185,  189,  192,  190,  193,
      168,  173,  175,  172,  176,  191,  194,  179,  195,  196,
      197,  187,  171,  189,  180,  177,  174,  175,  178,  190,
      186,  198,  199,  201,  183,  194,  191,  203,  193,  204,
      196,  206,  192,  208,  207,  210,  195,  209,  212,  211,
      213,  214,  215,  216,  201,  198,  217,  197,  218,  219,
      199,  223,  220,  221,  208,  222,  224,  213,  210,  206,
      211,  203,  216,  204,  207,  204,  203,  209,  228,  212,
      225,  212,  229,  224,  231,  214,  232,  230,  218,  215,
      233,  223,  218,  219,  234,  217,  220,  221,  237,  222,

      235,  225,  238,  239,  240,  228,  241,  229,  230,  243,
      244,  245,  248,  249,  251,  250,  252,  255,  257,  238,
      231,  258,  232,  256,  259,  260,  233,  237,  262,  234,
      243,  235,  266,  261,  275,  244,  250,  248,  240,  245,
      239,  252,  241,  267,  270,  273,  274,  276,  257,  249,
      251,  262,  279,  255,  261,  256,  280,  281,  282,  260,
      259,  258,  262,  277,  276,  284,  283,  286,  266,  291,
      287,  288,  292,  275,  295,  294,  282,  267,  270,  273,
      274,  296,  299,  300,  277,  283,  279,  298,  302,  305,
      280,  287,  288,  281,  306,  292,  308,  309,  311,  313,

      312,  284,  315,  286,  291,  294,  299,  317,  298,  302,
      318,  295,  319,  321,  309,  306,  320,  296,  300,  312,
      323,  322,  324,  315,  325,  305,  326,  318,  327,  333,
      308,  330,  329,  313,  311,  331,  331,  332,  335,  348,
      336,  317,  322,  338,  320,  325,  319,  321,  326,  337,
      340,  342,  324,  347,  323,  329,  330,  336,  345,  345,
      332,  349,  350,  327,  333,  351,  354,  340,  353,  355,
      337,  357,  358,  348,  335,  359,  342,  360,  338,  364,
      362,  349,  363,  350,  347,  353,  368,  365,  370,  371,
      373,  374,  359,  377,  355,  351,  378,  379,  360,  380,

      357,  362,  354,  363,  365,  383,  382,  358,  374,  384,
      384,  368,  387,  388,  364,  393,  380,  378,  394,  371,
      395,  377,  392,  392,  383,  396,  373,  382,  398,  370,
      402,  403,  404,  379,  410,  393,  405,  407,  406,  412,
      409,  395,  387,  413,  388,  417,  419,  398,  428,  418,
      422,  427,  394,  396,  443,  410,  407,  431,  412,  445,
      426,  430,  430,  436,  402,  448,  405,  444,  444,  404,
      409,  419,  403,  406,  443,  422,  446,  413,  426,  417,
      418,  427,  436,  449,  428,  450,  451,  431,  452,  457,
      454,  455,  448,  445,  456,  446,  462,  458,  465,  476,

      579,  479,  477,  481,  472,  473,  480,  482,  488,  493,
      494,  483,  495,  501,  501,  450,  458,  457,  497,  449,
      454,  455,  451,  452,  456,  472,  473,  477,  482,  480,
      473,  462,  483,  488,  465,  476,  479,  506,  513,  481,
      514,  519,  495,  541,  493,  494,  570,  578,  577,  497,
      576,  570,  575,  574,  541,  573,  569,  568,  567,  566,
      565,  513,  564,  562,  560,  559,  558,  557,  506,  556,
      514,  519,  591,  555,  554,  591,  592,  553,  592,  593,
      593,  594,  552,  551,  594,  550,  548,  547,  546,  545,
      544,  543,  542,  538,  537,  536,  535,  534,  533,  532,

      531,  530,  529,  528,  527,  526,  525,  524,  522,  521,
      520,  516,  515,  512,  511,  510,  509,  508,  507,  505,
      504,  503,  502,  500,  499,  498,  496,  492,  491,  490,
      489,  487,  486,  485,  484,  478,  475,  474,  471,  470,
      468,  467,  466,  464,  461,  460,  459,  453,  447,  442,
      441,  440,  439,  438,  437,  435,  434,  433,  432,  429,
      425,  424,  423,  421,  420,  416,  415,  414,  411,  408,
      401,  400,  399,  397,  391,  390,  389,  386,  385,  381,
      376,  375,  372,  369,  367,  366,  361,  356,  352,  346,
      344,  343,  341,  339,  334,  328,  316,  314,  310,  307,

      304,  303,  301,  297,  293,  290,  289,  285,  278,  272,
      271,  269,  268,  265,  264,  263,  254,  253,  247,  246,
      242,  236,  227,  226,  205,  202,  200,  188,  184,  182,
      181,  163,  138,  136,  135,  134,  132,  130,  101,   91,
       89,   58,   49,   48,   45,   33,   22,   17,   14,    8,
        7,    3,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,  590,  590,  590,  590,  590,  590,  590,  590,  590

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "parser/patterns.l"
#line 4 "parser/patterns.l"
#include "token.h"
#line 884 "parser/calc.lexer.c"
#line 885 "parser/calc.lexer.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 7 "parser/patterns.l"

#line 1104 "parser/calc.lexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 591 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1053 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 8 "parser/patterns.l"
{return CREATE;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 9 "parser/patterns.l"
{return TABLE;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 11 "parser/patterns.l"
{return DROP;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 13 "parser/patterns.l"
{return ALTER;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 14 "parser/patterns.l"
{return ADD;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 16 "parser/patterns.l"
{return ASSERTION;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 18 "parser/patterns.l"
{return VIEW;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 19 "parser/patterns.l"
{return AS;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 21 "parser/patterns.l"
{return INDEX;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 22 "parser/patterns.l"
{return ON;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 24 "parser/patterns.l"
{return TRIGGER;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 25 "parser/patterns.l"
{return REFERENCING;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 26 "parser/patterns.l"
{return BEFORE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 27 "parser/patterns.l"
{return UPDATE;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 28 "parser/patterns.l"
{return OF;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 29 "parser/patterns.l"
{return AFTER;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 30 "parser/patterns.l"
{return INSTEAD;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 31 "parser/patterns.l"
{return INSERT;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 32 "parser/patterns.l"
{return DELETE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 33 "parser/patterns.l"
{return OLD;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 34 "parser/patterns.l"
{return ROW;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 35 "parser/patterns.l"
{return NEW;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 36 "parser/patterns.l"
{return FOR;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 37 "parser/patterns.l"
{return EACH;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 38 "parser/patterns.l"
{return STATEMENT;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 39 "parser/patterns.l"
{return WHEN;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 40 "parser/patterns.l"
{return BEGINTOKEN;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 41 "parser/patterns.l"
{return END;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 43 "parser/patterns.l"
{return UNIQUE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 44 "parser/patterns.l"
{return PRIMARYKEY;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 45 "parser/patterns.l"
{return CHECK;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 46 "parser/patterns.l"
{return FOREIGNKEY;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 47 "parser/patterns.l"
{return REFERENCES;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 48 "parser/patterns.l"
{return NOT_DEFERRABLE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 49 "parser/patterns.l"
{return DEFERED_DEFERRABLE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 50 "parser/patterns.l"
{return IMMEDIATE_DEFERRABLE;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 51 "parser/patterns.l"
{return UPDATE_NULL;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 52 "parser/patterns.l"
{return UPDATE_CASCADE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 53 "parser/patterns.l"
{return DELETE_NULL;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 54 "parser/patterns.l"
{return DELETE_CASCADE;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 55 "parser/patterns.l"
{return CONSTRAINT;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 56 "parser/patterns.l"
{return DEFAULT;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 58 "parser/patterns.l"
{return STAR;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 59 "parser/patterns.l"
{return SUM;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 60 "parser/patterns.l"
{return AVG;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 61 "parser/patterns.l"
{return MIN;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 62 "parser/patterns.l"
{return MAX;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 63 "parser/patterns.l"
{return COUNT;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 64 "parser/patterns.l"
{return DISTINCT;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 66 "parser/patterns.l"
{return PLUS;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 67 "parser/patterns.l"
{return SUBTRACT;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 68 "parser/patterns.l"
{return DIVISION;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 69 "parser/patterns.l"
{return CONCATENATION;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 71 "parser/patterns.l"
{return CHAR;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 72 "parser/patterns.l"
{return VARCHAR;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 73 "parser/patterns.l"
{return BIT;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 74 "parser/patterns.l"
{return BITVARYING;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 75 "parser/patterns.l"
{return BOOLEAN;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 76 "parser/patterns.l"
{return INT;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 77 "parser/patterns.l"
{return INTEGER;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 78 "parser/patterns.l"
{return SHORTINT;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 79 "parser/patterns.l"
{return FLOAT;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 80 "parser/patterns.l"
{return REAL;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 81 "parser/patterns.l"
{return DOUBLEPRECISION;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 82 "parser/patterns.l"
{return DECIMAL;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 83 "parser/patterns.l"
{return NUMERIC;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 84 "parser/patterns.l"
{return DATE;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 85 "parser/patterns.l"
{return TIME;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 87 "parser/patterns.l"
{return LIKE;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 88 "parser/patterns.l"
{return IN;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 89 "parser/patterns.l"
{return ALL;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 90 "parser/patterns.l"
{return ANY;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 91 "parser/patterns.l"
{return IS;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 92 "parser/patterns.l"
{return EXISTS;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 94 "parser/patterns.l"
{return EQUAL;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 95 "parser/patterns.l"
{return NOTEQUAL;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 96 "parser/patterns.l"
{return LESS;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 97 "parser/patterns.l"
{return GREATER;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 98 "parser/patterns.l"
{return LESSEQUAL;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 99 "parser/patterns.l"
{return GREATEREQUAL;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 101 "parser/patterns.l"
{return AND;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 102 "parser/patterns.l"
{return OR;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 104 "parser/patterns.l"
{return DOT;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 106 "parser/patterns.l"
{return ELSEIF;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 107 "parser/patterns.l"
{return CALL;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 108 "parser/patterns.l"
{return THEN;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 109 "parser/patterns.l"
{return IF;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 110 "parser/patterns.l"
{return ELSE;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 111 "parser/patterns.l"
{return CURSOR;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 112 "parser/patterns.l"
{return DO;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 113 "parser/patterns.l"
{return RETURN;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 114 "parser/patterns.l"
{return SET;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 115 "parser/patterns.l"
{return OUT;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 116 "parser/patterns.l"
{return INOUT;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 117 "parser/patterns.l"
{return DECLARE;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 118 "parser/patterns.l"
{return PROCEDURE;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 119 "parser/patterns.l"
{return FUNCTION;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 120 "parser/patterns.l"
{return RETURNS;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 122 "parser/patterns.l"
{return FROM;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 123 "parser/patterns.l"
{return WHERE;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 125 "parser/patterns.l"
{return INSERTINTO;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 126 "parser/patterns.l"
{return VALUES;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 128 "parser/patterns.l"
{return START;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 129 "parser/patterns.l"
{return TRANSACTION;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 130 "parser/patterns.l"
{return COMMIT;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 131 "parser/patterns.l"
{return ROLLBACK;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 132 "parser/patterns.l"
{return SHOW;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 133 "parser/patterns.l"
{return TABLES;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 134 "parser/patterns.l"
{return ASSERTIONS;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 135 "parser/patterns.l"
{return VIEWS;}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 136 "parser/patterns.l"
{return INDEXS;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 137 "parser/patterns.l"
{return TRIGGERS;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 138 "parser/patterns.l"
{return FUNCTIONS;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 139 "parser/patterns.l"
{return PROCEDURES;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 140 "parser/patterns.l"
{return USER;}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 141 "parser/patterns.l"
{return PASSWORD;}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 142 "parser/patterns.l"
{return CONNECT;}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 144 "parser/patterns.l"
{return ASC;}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 145 "parser/patterns.l"
{return DESC;}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 146 "parser/patterns.l"
{return CROSS;}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 147 "parser/patterns.l"
{return JOIN;}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 148 "parser/patterns.l"
{return NATURAL;}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 149 "parser/patterns.l"
{return FULL;}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 150 "parser/patterns.l"
{return OUTER;}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 151 "parser/patterns.l"
{return LEFT;}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 152 "parser/patterns.l"
{return RIGHT;}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 153 "parser/patterns.l"
{return SELECT;}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 154 "parser/patterns.l"
{return GROUPBY;}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 155 "parser/patterns.l"
{return HAVING;}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 156 "parser/patterns.l"
{return ORDERBY;}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 157 "parser/patterns.l"
{return LIMIT;}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 158 "parser/patterns.l"
{return UNION;}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 159 "parser/patterns.l"
{return DIFFERENCE;}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 160 "parser/patterns.l"
{return INTERSECTION;}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 162 "parser/patterns.l"
{return INTVALUE;}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 163 "parser/patterns.l"
{return FLOATVALUE;}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 164 "parser/patterns.l"
{return STRINGVALUE;}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 165 "parser/patterns.l"
{return BOOLVALUE;}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 167 "parser/patterns.l"
{return SEMICOLON;}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 168 "parser/patterns.l"
{return LPAREN;}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 169 "parser/patterns.l"
{return RPAREN;}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 170 "parser/patterns.l"
{return COMMA;}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 171 "parser/patterns.l"
{return NOT;}
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 172 "parser/patterns.l"
{return NULLMARK;}
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 173 "parser/patterns.l"
{return ID;}
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 174 "parser/patterns.l"
{return PASSWORDS;}
	YY_BREAK
case 147:
/* rule 147 can match eol */
YY_RULE_SETUP
#line 175 "parser/patterns.l"
{/*ignore space*/}
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 176 "parser/patterns.l"
ECHO;
	YY_BREAK
#line 1902 "parser/calc.lexer.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 591 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 591 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 590);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 176 "parser/patterns.l"

